#!/usr/bin/env bash
# Render /tmp/env.env from a secrets JSON dump. Called by the deploy
# workflow. PROJECT-SPECIFIC — add new env vars here as the project grows.
#
# Args:
#   $1   target env: prod (only prod exists for tradebot-mini)
#   $2   output path
#
# Caller-provided env:
#   SECRETS_JSON   toJSON(secrets)
#   SERVER_IMAGE   docker image tag of the just-built tradebot image

set -euo pipefail

target_env="${1:?usage: $0 prod <output_path>}"
out="${2:?usage: $0 prod <output_path>}"

[ "$target_env" = "prod" ] || { echo "❌ only 'prod' supported" >&2; exit 1; }

secret() { jq -r ".$1 // empty" <<< "$SECRETS_JSON"; }
require() { [ -n "$1" ] || { echo "❌ missing: $2" >&2; exit 1; }; }

# Required for the bot itself.
deepseek_key=$(secret DEEPSEEK_KEY)
alpaca_key=$(secret ALPACA_API_KEY)
alpaca_secret=$(secret ALPACA_API_SECRET)
alpaca_api_endpoint=$(secret ALPACA_API_ENDPOINT)
alpaca_data_endpoint=$(secret ALPACA_DATA_ENDPOINT)
twitter_consumer_key=$(secret TWITTER_API_CONSUMER_KEY)
twitter_secret_key=$(secret TWITTER_API_SECRET_KEY)
twitter_access_token=$(secret TWITTER_ACCESS_TOKEN)
twitter_token_secret=$(secret TWITTER_TOKEN_SECRET)
database_url=$(secret DATABASE_URL)

require "$deepseek_key"         DEEPSEEK_KEY
require "$alpaca_key"           ALPACA_API_KEY
require "$alpaca_secret"        ALPACA_API_SECRET
require "$alpaca_api_endpoint"  ALPACA_API_ENDPOINT
require "$alpaca_data_endpoint" ALPACA_DATA_ENDPOINT
require "$twitter_consumer_key" TWITTER_API_CONSUMER_KEY
require "$twitter_secret_key"   TWITTER_API_SECRET_KEY
require "$twitter_access_token" TWITTER_ACCESS_TOKEN
require "$twitter_token_secret" TWITTER_TOKEN_SECRET
require "$database_url"         DATABASE_URL
require "${SERVER_IMAGE:-}"     SERVER_IMAGE

# SearXNG signing secret — random per deploy is fine, sessions don't matter.
searxng_secret=$(openssl rand -hex 32)

cat > "$out" <<EOF
# Generated by build-env.sh — DO NOT EDIT BY HAND.
SERVER_IMAGE=${SERVER_IMAGE}

DEEPSEEK_KEY=${deepseek_key}

ALPACA_API_KEY=${alpaca_key}
ALPACA_API_SECRET=${alpaca_secret}
ALPACA_API_ENDPOINT=${alpaca_api_endpoint}
ALPACA_DATA_ENDPOINT=${alpaca_data_endpoint}

TWITTER_API_CONSUMER_KEY=${twitter_consumer_key}
TWITTER_API_SECRET_KEY=${twitter_secret_key}
TWITTER_ACCESS_TOKEN=${twitter_access_token}
TWITTER_TOKEN_SECRET=${twitter_token_secret}

DATABASE_URL=${database_url}

SEARXNG_SECRET=${searxng_secret}
# SEARXNG_URL/CRAWL4AI_URL come from docker-compose `environment:` block
# (they're internal hostnames, not secrets, so live there not here).
EOF

chmod 600 "$out"
echo "wrote $out"
